### ISSUE TITLE
The --group-albums feature tries to search for empty albums

### ISSUE THREAD

**Issue by JOJ0** [beetbox/beets#4640]
Tracks without empfy album information are tried to be grouped together in an album which leads to useless search results.

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (... paste here ...)
   prod  (beets)    ~/git/beets   master  beet import -t -g /remote/data/music-archive/DrumnbassJungleDrumfunk/0-Single-Tracks/Crossfire 

/remote/data/music-archive/DrumnbassJungleDrumfunk/0-Single-Tracks/Crossfire/crossfire - Battlefield.mp3
/remote/data/music-archive/DrumnbassJungleDrumfunk/0-Single-Tracks/Crossfire/Crossfire - Firebolt.mp3
/remote/data/music-archive/DrumnbassJungleDrumfunk/0-Single-Tracks/Crossfire/Crossfire - Hydra (Cell D Rmx)-2.mp3
/remote/data/music-archive/DrumnbassJungleDrumfunk/0-Single-Tracks/Crossfire/Crossfire - Lethal formz.mp3
/remote/data/music-archive/DrumnbassJungleDrumfunk/0-Single-Tracks/Crossfire/Crossfire - Nightscape.mp3
/remote/data/music-archive/DrumnbassJungleDrumfunk/0-Single-Tracks/Crossfire/Crossfire - Sword  Fight.mp3
/remote/data/music-archive/DrumnbassJungleDrumfunk/0-Single-Tracks/Crossfire/Crossfire_-_Northern_Lightz.mp3 (7 items)
Finding tags for album " - ".
Candidates:
1. Marco Wellisch - Shambakla (30.7%) (tracks, album, artist, ...) (Beatport, Digital, 2021, Moehre Rekorder, MORE009)
2. Issam Ogur - Antares (29.0%) (album, artist, tracks, ...) (Beatport, Digital, 2022, Krad Records, KRD380)
3. aetos - Symphonies Of December (17.7%) (album, artist, unmatched tracks, ...) (Beatport, Digital, 2021, recordJet, RLS00178501)
4. Charmes - Doing To Me (15.5%) (unmatched tracks, album, artist, ...) (Beatport, Digital, 2022, IN CONTROL RECORDINGS, ICR056)
5. Fanfickk - Feel Better (Waker Remix) (15.3%) (unmatched tracks, album, artist, ...) (Beatport, Digital, 2021, recordJet, RLS00177899)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates, plaY? 
```

### Setup

* OS: Manjaro 
* Python version: 3.10.8
* beets version: 10.6.1 git-master
* Turning off plugins made problem go away: no 

My configuration (output of `beet config`) is:

- I'll post a longish config once we decide it would help.

**Comment by sampsyo** [comment]
Yeah, this is annoying behavior. In fact, this goes beyond just `--group-albums`: even in the "normal" album import mode, it's possible for albums to be missing metadata altogether, resulting in exactly the same confusing search.

Maybe the solution is to do some kind of warning, like you suggest, but totally decoupled from `--group-albums`: just do it before searching if we ever are truly metadata-free, which would result in a meaningless search?

**Comment by JOJ0** [comment]
I once built an early exit if artist _and_ album is missing into `candidates` method of the Discogs plugin. Probably a solution as you suggest that covers MusicBrainz as well as all metadata source plugins is the way to go and would then replace that for that particular plugin and provide it for all the other plugins. I'll see if I get around to getting an implementation started and in them meantime wait and hope somebody else picks it up. I'd be happy to review a PR.

**Comment by pioneerHitesh** [comment]
@JOJ0 This issue is fixed 
```No matching release found for 2 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch```

**Comment by JOJ0** [comment]
> @JOJ0 This issue is fixed 
> 
> ``No matching release found for 2 tracks.
> 
> For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch``

I'm not sure I understand? Why are you sure it is fixed? And why does the output you posted proove that? Please elaborate! Thanks:-)

**Comment by Vrihub** [comment]
This is still happening and very annoying. I'm experiencing this with musicbrainz, but I guess it happens with other autotagging extensions.

I think we should skip the initial automatic search when there is no artist and no album and no `search_ids` (see `/beets/autotag/match.py`).

The exclusion should only apply to autotagging extensions that perform time-consuming online searches that need at least artist or album or an id, i.e. all but `chroma` and `fromfilename` (if the list at https://beets.readthedocs.io/en/stable/plugins/index.html#autotagger-extensions is complete).
