### ISSUE TITLE
Web plugin error when playing or downloading a song

### ISSUE THREAD

**Issue by miertla** [beetbox/beets#4818]
### Problem

Running the `beet web` command, then searching for a song or artist in my library, and then clicking the `play button` led to this problem:

<img width="811" alt="Screenshot 2023-06-11 at 9 29 17 PM" src="https://github.com/beetbox/beets/assets/55955381/5d55e8df-b1a4-4ace-9436-2a363249c0e8">

When I click the `download link` it led to this problem (command line 404 above) in my web browser:

<img width="1000" alt="Screenshot 2023-05-30 at 10 42 39 PM" src="https://github.com/beetbox/beets/assets/55955381/e9568644-092d-44ae-836c-2ac950de8759">

This happens with all of the music files in my library I’ve tested so far, and I’ve tested different artist and songs.

### Setup

* OS: macOS Venture 13.4
* Python version: 3.8.11
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

<img width="397" alt="Screenshot 2023-06-11 at 9 52 50 PM" src="https://github.com/beetbox/beets/assets/55955381/4d496fb7-e78d-4499-b5a0-eb93a3c46d4a">

**Comment by jackwilsdon** [comment]
It seems like the `attachment_filename` parameter was renamed in Flask 2: https://github.com/pallets/flask/blame/cfa863c357c4a40cfc11fe1b9a4f36d8e75cf52f/src/flask/helpers.py#L446-L449

**Comment by miertla** [comment]
My Flask version is 2.3.2 when I run the command `flask --version`. When I went to that section in the code I don't see anywhere that 'attachment_filename' is referenced. Line 324 is: `base_filename.encode("latin-1", "strict")`. So I'm still not sure why this is happening, but am trying to find a solution to fix it which might be something on my end.

**Comment by jackwilsdon** [comment]
Actually it seems like this has already been fixed in #4433. There hasn't been a release since this change, so you'll need to run the [latest source version of beets](https://beets.readthedocs.io/en/stable/faq.html#run-the-latest-source-version-of-beets) to use the fix.

**Comment by miertla** [comment]
I came across that PR when I was trying to resolve my issue. I have the latest version of beets installed (1.6.0) and it has the updates in that PR so I'm not sure why it's still not working. It must be something else that's causing this error. I appreciate the help!

**Comment by jackwilsdon** [comment]
That PR isn't included in 1.6.0 - it was merged after that release.

**Comment by miertla** [comment]
I meant that I didn't install beets until after the date this PR was merged with the main branch. Is there something else that I need to do to update my local copy? I checked the files edited and mine match what's in this PR.
